name: Android CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"  # Отключаем фонтовый процесс для CI

    steps:
    # Шаг 1: Загрузка кода
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Установка JDK (LTS-версия)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'  # Кеширование зависимостей

    # Шаг 3: Права на выполнение gradlew
    - name: Make gradlew executable
      run: chmod +x gradlew

    # Шаг 4: Сборка Debug APK
    - name: Build Debug APK
      run: |
        ./gradlew clean assembleDebug --no-daemon --stacktrace --info
        ls -la app/build/outputs/apk/debug/  # Проверка наличия APK

    # Шаг 5: Загрузка артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error  # Прерывание при отсутствии APK
        retention-days: 7  # Автоудаление через неделю
